<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click here to Download File</name>
   <tag></tag>
   <elementGuidId>fad7ded6-9129-4198-8a0a-351e19ef24a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.control-group > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[28]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>154ff248-6ce6-4c86-aa01-8056bcacb878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com/stanfy/behave-rest/blob/master/features/conf.yaml</value>
      <webElementGuid>725824a4-85b5-4688-ac0c-2c2362420fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to Download File</value>
      <webElementGuid>60caa47b-fbd1-455f-a26e-788fcaf74a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-body-3077692503353518311&quot;)/div[1]/div[1]/div[1]/h2[2]/div[1]/div[1]/div[@class=&quot;controls&quot;]/div[@class=&quot;control-group&quot;]/div[@class=&quot;control-group&quot;]/a[1]</value>
      <webElementGuid>76d047a5-c4f1-4e9f-b623-f12e9a5fbd00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[28]/div[2]/div/a</value>
      <webElementGuid>541db049-1175-4e89-b1e9-93c5543c9526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Click here to Download File')]</value>
      <webElementGuid>79fb120d-179c-488b-bc85-2e1e27afb1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com/stanfy/behave-rest/blob/master/features/conf.yaml')]</value>
      <webElementGuid>e404f871-27b3-4599-98b6-b493d9d90c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div[2]/div/a</value>
      <webElementGuid>88fbf96b-cdad-41cc-8281-1253a98b5976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://github.com/stanfy/behave-rest/blob/master/features/conf.yaml' and (text() = 'Click here to Download File' or . = 'Click here to Download File')]</value>
      <webElementGuid>ec4b3cb6-7efb-4aa5-8370-f6658f1a34a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
