<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_exp</name>
   <tag></tag>
   <elementGuidId>f5469f3b-eedc-4513-a685-41fe6d48505a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97363b66-b071-4d3f-a8fa-96597c605ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp-1</value>
      <webElementGuid>768e6bff-5722-4d8a-a7f4-9836be9c7a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp</value>
      <webElementGuid>7c7a945d-3909-4885-9e01-930b14fa74e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ea5d483e-69dc-4146-99cf-a630623295f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2c1cc626-c178-4880-86e7-6650ca272c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp-1&quot;)</value>
      <webElementGuid>4b4e5c61-7fe4-47d6-8d79-f83c8d62e3bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp-1']</value>
      <webElementGuid>e8273f32-fa08-40d7-a0c3-8860afdde1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[14]/input[2]</value>
      <webElementGuid>2bd4e93f-fb58-4367-b021-5312318f49fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input[2]</value>
      <webElementGuid>c97ef34b-1257-494d-a39f-06fa17028e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exp-1' and @name = 'exp' and @type = 'radio']</value>
      <webElementGuid>ba2c7c17-500d-4d20-94af-d11644c64745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
