<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sex</name>
   <tag></tag>
   <elementGuidId>2d72d7b2-fd47-4c21-bf22-b46610a7dd7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sex-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sex-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3de4db69-5168-4ede-ac83-05a434f8cab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sex-0</value>
      <webElementGuid>edc3b91d-f896-40c1-9666-aa0ee774e6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>82b3ad6d-6ddb-4207-a7fe-c5cd4bdccd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bac1839d-eb38-4113-8b0b-d19dcf3ccb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>55f21da7-9064-4c5e-8b67-88a3d6bd128d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sex-0&quot;)</value>
      <webElementGuid>d682e24f-6fa8-4ea2-b636-5af32f4cb689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sex-0']</value>
      <webElementGuid>11411986-db63-4d0d-abf5-541932841c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[9]/input</value>
      <webElementGuid>390a3c1a-9d60-4032-8d47-acd13be9a6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>041609bb-b32d-4ff2-9c20-e0609ba310be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sex-0' and @name = 'sex' and @type = 'radio']</value>
      <webElementGuid>c7e34034-d5f7-4568-a296-e6b867dc2219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
