<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Browser CommandsNavigation CommandsS_69f390</name>
   <tag></tag>
   <elementGuidId>dd3107fe-6cea-406f-8fbe-1257770ed622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selenium_commands</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selenium_commands']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c92a638-7604-40a7-9398-ca8ae8a2e8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>5c6c9f6f-60b4-40fe-9c30-803ccac8077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>2aef4078-dce4-4fee-ace1-dbdb8cdf5b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>6524dfc0-0bab-4a18-b6c4-3bc8cfdd4ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands</value>
      <webElementGuid>ce66e404-d7d2-4ee9-9e41-9f384752dbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selenium_commands&quot;)</value>
      <webElementGuid>4c518003-4e72-405e-951b-626aca4d4bff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selenium_commands']</value>
      <webElementGuid>5a05d522-3d1d-4a41-b724-b844cb7534aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[27]/div[2]/select</value>
      <webElementGuid>7b88cad2-14cb-4626-9ede-9ee921c7e830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/select</value>
      <webElementGuid>47e67fdc-018d-41dc-88aa-93634b6f64cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selenium_commands' and @name = 'selenium_commands' and (text() = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands' or . = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands')]</value>
      <webElementGuid>3034b6c6-1078-41e8-8ec9-a68f81a7c166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
