<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AsiaEuropeAfricaAustraliaSouth Ameri_982c86</name>
   <tag></tag>
   <elementGuidId>005e39ff-80a0-4dd9-b9a5-616940cf260f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continents</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='continents']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad018227-ca82-41e5-aeeb-20ba68358a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>e71962ed-3cf6-4491-abb9-3d8f1cbdaa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>9367d7f8-d483-4266-bbb0-bb0f101724ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>a4ceb422-71f9-4306-8411-31061a677c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica</value>
      <webElementGuid>90e7d6fd-81bb-4f46-af93-9479e80fb2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continents&quot;)</value>
      <webElementGuid>2cfbf48e-8a1f-46c8-b3e7-2f54d0809499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='continents']</value>
      <webElementGuid>afbff27a-d188-47a5-927e-9779c19d6f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[25]/div[2]/select</value>
      <webElementGuid>482229c0-cd23-4775-ad8f-f3ffcf19bdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>20484e0d-76c3-41d0-8db2-403b7d103cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'continents' and @name = 'continents' and (text() = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica' or . = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica')]</value>
      <webElementGuid>4c08e35e-1b42-418a-be16-f8da6a7cc1e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
