<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_profession</name>
   <tag></tag>
   <elementGuidId>ac15b0a5-14dc-4fff-b015-6557daa5571a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profession-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profession-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62ce538b-abd0-4820-8c60-f11084aa2479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profession-1</value>
      <webElementGuid>97fda116-33f9-4ec3-86bd-024953c4b334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profession</value>
      <webElementGuid>1304b1ba-a97a-458d-b4af-11b5662c8e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2f28f93f-e90d-4ef5-904c-730ae8d272a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Automation Tester</value>
      <webElementGuid>fb4abf7a-99cb-4da6-abdc-96c0df0a4581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profession-1&quot;)</value>
      <webElementGuid>b8fdf10a-89d7-4953-bbe6-06252a4e9fa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profession-1']</value>
      <webElementGuid>f0fd9ce2-5a19-48e9-8f2e-0f21b2d9fe54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[20]/input[2]</value>
      <webElementGuid>64e2380b-b3c4-49dd-921a-50bfa2d783c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/input[2]</value>
      <webElementGuid>23a32f40-b46d-4fc9-ba6d-f1f602ac666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profession-1' and @name = 'profession' and @type = 'checkbox']</value>
      <webElementGuid>97e3c28b-db05-4bd6-8859-8a363b358b0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
