<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tool</name>
   <tag></tag>
   <elementGuidId>92759594-95c5-435b-9996-d3117b81019d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tool-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d4ed925-bdde-4016-a7b6-1b092dba511b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-0</value>
      <webElementGuid>d5c2ac60-b3d4-429f-8dfa-de359c8081b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>e5ab4d14-c6d7-4073-af53-56b13028c753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a49977aa-1626-48e9-9420-eff0c9fb211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QTP</value>
      <webElementGuid>f77352ed-449d-479e-b225-9ebe2e841541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-0&quot;)</value>
      <webElementGuid>4386904c-665b-4819-b3c3-b9f1a77c9261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tool-0']</value>
      <webElementGuid>f90adadb-a896-4adb-82ce-7edd62467ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[22]/input</value>
      <webElementGuid>a0d90fca-5ca1-4c7e-8ef1-e15e8bc24856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input</value>
      <webElementGuid>d3e69357-73c8-4561-945c-36ea08b602cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tool-0' and @name = 'tool' and @type = 'checkbox']</value>
      <webElementGuid>ed238001-86ec-4674-b118-de562269bb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
