<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Browser CommandsNavigation CommandsS_69f390</name>
   <tag></tag>
   <elementGuidId>602b3e25-370a-4ff9-976e-aae4fd94c585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selenium_commands</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selenium_commands']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7084161-b9b6-4e36-a76e-33d775290e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>f575794a-ffcd-4953-a248-670de9bdaf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>18619d52-f07b-4286-80a4-68f6bd0185d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>395ed0f1-a7b5-4eb3-a88a-daba2a3526b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands</value>
      <webElementGuid>1423ccfc-afc2-4f2f-a81a-af6acc71104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selenium_commands&quot;)</value>
      <webElementGuid>dbf3942f-30f2-4759-875c-ac2d6622b498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selenium_commands']</value>
      <webElementGuid>bb2cf169-b36b-4918-9061-ef3c3c05b61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[27]/div[2]/select</value>
      <webElementGuid>87505290-4518-4b75-9fc4-b27cf8805720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/select</value>
      <webElementGuid>3c5d37f3-97ee-4c44-9208-f4fac7aac22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selenium_commands' and @name = 'selenium_commands' and (text() = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands' or . = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands')]</value>
      <webElementGuid>91120bec-94d9-41fd-bb58-59958595ab1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
