<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Years of Experience_exp</name>
   <tag></tag>
   <elementGuidId>e41dc072-dd6a-400d-9773-5bd6c4add4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3750ea22-29a4-4c71-b54c-2c9a877d66b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp-0</value>
      <webElementGuid>161106e2-1c76-476f-8874-28b88673d63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp</value>
      <webElementGuid>612d8e2e-4904-486b-a929-d0c37422af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bc17e605-9216-4223-a353-2954dfd0da21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>468a80b6-05db-44a2-a15d-ee97bfe44c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp-0&quot;)</value>
      <webElementGuid>143d7581-bfb1-4b81-a98d-e7a5bd8e3d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp-0']</value>
      <webElementGuid>c8e5cae9-ad75-4c12-b263-23cfdb74aac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[14]/input</value>
      <webElementGuid>3a158a4d-69d7-4716-91fa-573a54b6f0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>b894aba8-258c-470d-8452-7b1734b18be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exp-0' and @name = 'exp' and @type = 'radio']</value>
      <webElementGuid>5d294038-685e-4623-92cb-ada28f28e33b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
