<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Tools_tool</name>
   <tag></tag>
   <elementGuidId>2db9c10d-cdcf-4880-a962-4e228b0df88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tool-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b73a4638-66f2-4fbe-bd44-e0943b413f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-0</value>
      <webElementGuid>d23ad9b6-0411-4280-bc15-20a92dbbb568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>7fc522b1-54d5-4690-935c-41b8823b9af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>da773022-85d4-43e1-ba77-03f754cceba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QTP</value>
      <webElementGuid>c1701589-2a2b-48ee-a975-3ebf1fc22f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-0&quot;)</value>
      <webElementGuid>ce835a28-db54-4aec-a032-30b60f4566f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tool-0']</value>
      <webElementGuid>bc87ae99-ea18-481d-997d-3dd4cc6a0a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[22]/input</value>
      <webElementGuid>3d75e839-befd-429e-b2f6-04c8bb8691b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input</value>
      <webElementGuid>cf3a4c02-c486-4097-acf6-4fde79c34e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tool-0' and @name = 'tool' and @type = 'checkbox']</value>
      <webElementGuid>b041dd7d-7c28-402d-879d-a673ccf0ae80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
