<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Image_photo</name>
   <tag></tag>
   <elementGuidId>bb557dbc-5634-4fce-9eb8-cff18489eff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='photo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cda80ba-5ef5-4201-beea-7d49c9334198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-file</value>
      <webElementGuid>d2d2c3b2-7a79-4b69-9661-b0d7eb9499d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>photo</value>
      <webElementGuid>8510ba64-0a5f-4da1-8718-b214b6c5d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>photo</value>
      <webElementGuid>6a2073ce-cc04-408f-908a-d9242232aac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>77be8f48-ccfb-4019-8840-79389a43179b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photo&quot;)</value>
      <webElementGuid>dae5cc24-e980-4cca-9d30-3c5814c899b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='photo']</value>
      <webElementGuid>8728a2b2-ae7d-434d-977a-d6ce03ef7d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[28]/div[2]/input</value>
      <webElementGuid>66f23e4b-2b82-4cfd-a3de-adf4ec342ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div[2]/input</value>
      <webElementGuid>43d1a97c-7343-4467-8558-d9b86ded170c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'photo' and @name = 'photo' and @type = 'file']</value>
      <webElementGuid>34af84ac-ee9c-464a-9fa3-9d32d287c1b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
