<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands</name>
   <tag></tag>
   <elementGuidId>a53131e5-b78c-44be-b09b-41cb8730c6df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selenium_commands</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selenium_commands']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a6c107cd-572b-415f-b77a-e64226392d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>f11b3bdf-780b-4111-a551-020d2a6ff5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>14818658-4acb-4953-88e5-a0c6810a7c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selenium_commands</value>
      <webElementGuid>e85022ec-261f-4d55-92ee-96d1f19601a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands</value>
      <webElementGuid>7874a828-bfcc-43e4-b2ab-bb0ff8a24597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selenium_commands&quot;)</value>
      <webElementGuid>f4bacdd5-8746-4754-855b-2d0b9f0d12a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selenium_commands']</value>
      <webElementGuid>1e57e0ff-0be9-4ecd-b9fd-978c165b8116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[27]/div[2]/select</value>
      <webElementGuid>84edf49e-28bb-4c09-adba-b617db107d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/select</value>
      <webElementGuid>dd7b73f0-bc2c-4eb6-9ae8-3ae184bc4208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selenium_commands' and @name = 'selenium_commands' and (text() = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands' or . = 'Browser CommandsNavigation CommandsSwitch CommandsWait CommandsWebElement Commands')]</value>
      <webElementGuid>b4f15ed4-8c68-4cbc-8aeb-bdc38961f1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
