<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica</name>
   <tag></tag>
   <elementGuidId>561858f7-6b69-43ee-970c-c44dccc50446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continents</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='continents']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>597f5045-378d-4255-abad-2b6c1c6d23ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>474aa487-14fc-49e5-b738-dff45f979324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>a9876e87-d762-4f9a-958f-dd109a7ff3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>e71aa92a-52c4-4b44-bc07-5520360605ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica</value>
      <webElementGuid>f4f6b4c1-4246-4190-8f5e-b7f882f07a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continents&quot;)</value>
      <webElementGuid>7326f7dd-4939-490e-85ec-a8e5a4eb66ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='continents']</value>
      <webElementGuid>25265aad-5327-4b14-8e16-83559fed0c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[25]/div[2]/select</value>
      <webElementGuid>ed293cf2-3182-49e5-ab01-77495fab869b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4a5fce50-529c-4b7b-9d41-d9038dbebdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'continents' and @name = 'continents' and (text() = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica' or . = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica')]</value>
      <webElementGuid>6d66b4da-b62a-4279-93c3-2747117006df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
